name : CI/CD Pipeline

On :
  push:
    branches:
      - main

jobs :
  test: {
    runs-on: ubuntu-latest
    steps: [
      {
        name: Checkout code
        uses: actions/checkout@v2
      },
      {
        name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
          cache: 'yarn'
          cache-dependency-path: 'yarn.lock'
      },
      {
        name: Install dependencies
        working-directory: ./app
        run: yarn install
      },
      {
        name: Run tests
        working-directory: ./app
        run: yarn test
      }
    ]
  }

  build: {}
  
  deploy: {}